### ISSUE TITLE
MCU Firmware source

### ISSUE THREAD

**Issue by itskarthig** [Lora-net/gateway_2g4_hal#3]
Hi,

Where I Can find the Source Code

https://github.com/Lora-net/gateway_2g4_hal/tree/master/mcu_bin

Thanks
KarthiG

**Comment by mcoracin** [comment]
Hello,
The source code for the MCU is not available yet, but will be with the next official release of this project.
I don't have a clear date for now.
Best regards,
Michael

**Comment by itskarthig** [comment]
Thanks @mcoracin
