### ISSUE TITLE
latest sx1280 driver

### ISSUE THREAD

**Issue by JiapengLi** [Lora-net/gateway_2g4_hal#4]
It looks like sx1280 datasheet has been updated early this year. 
Is it possible to get a copy of the latest SX1280 driver?

![image](https://user-images.githubusercontent.com/3773923/103150708-7a34db80-47b1-11eb-958b-a0423350a972.png)

The latest sx1280 driver I could find online is from 2018. 

https://os.mbed.com/teams/Semtech/code/SX1280Lib/

https://semtech.my.salesforce.com/sfc/p/E0000000JelG/a/2R0000001NRn/tQu.OZ5Ki9VIopP.20HQEhIVkF.1Id57vsBSqlJ_eaU?__hstc=212684107.2d2879742be64dacfb218ddefcfded5b.1605841645633.1605841645633.1608976077075.2&__hssc=212684107.2.1608976077075&__hsfp=4215168121

![image](https://user-images.githubusercontent.com/3773923/103150770-16f77900-47b2-11eb-820e-8f61daec485d.png)

**Comment by mcoracin** [comment]
The purpose of this project is not to provide a sx1280 driver. please reach Semtech support for that.
