### ISSUE TITLE
lgw_pkt_rx_s has field 'modulation', but lgw_pkt_tx_s has not?

### ISSUE THREAD

**Issue by brocaar** [Lora-net/gateway_2g4_hal#5]
The `lgw_pkt_rx_s` struct has a field named `modulation` with as type `e_modulation` (an enum with currently `MOD_LORA` as only option). I would have expected the same field in the `lgw_pkt_tx_s` struct. Even when the `e_modulation` has a single option, it would make it explicit which modulation is used for TX.

**Comment by mcoracin** [comment]
I agree, it is something we'll have to fix in next versions.
Thanks and regards
