### ISSUE TITLE
Why is 812kHz bandwidth mapped to BW_800KHZ?

### ISSUE THREAD

**Issue by brocaar** [Lora-net/gateway_2g4_hal#6]
https://lora-developers.semtech.com/library/tech-papers-and-guides/physical-layer-proposal-2.4ghz defines that the used bandwidth for the 2.4GHz channels is 812kHz. In the bandwidth enum however, this value does not exist:

```c
typedef enum {
    BW_200KHZ  = 8,
    BW_400KHZ  = 10,
    BW_800KHZ  = 12,
    BW_1600KHZ = 13
} e_bandwidth;
```

Looking at the `lora_pkt_fwd.c` source, I see that `800` and `812` kHz are mapped to `BW_800KHZ`.
https://github.com/Lora-net/gateway_2g4_hal/blob/master/packet_forwarder/src/lora_pkt_fwd.c#L317

```c
            switch (bw) {
                case 800000:
                case 812000:
                    rxconf.bandwidth = BW_800KHZ;
                    break;
                default:
                    MSG("ERROR: bandwidth %u not supported\n", bw);
                    return -1;
            }
```

Could you clarify this? E.g. why is the `BW_800KHZ` not named `BW_812KHZ` instead?

**Comment by mcoracin** [comment]
On the end-node side driver (sx1280 RAL), the bandwidth are defined like this (200, 400, 800, 1600), although the actual values 203, 406, 812, 1625.
So I wanted to be consistent with that on the gateway side HAL, but still support both in the packet forwarder.
